// The codec, against images this file builds byte by byte rather than through the encoder. That
// distinction is the point: a decoder checked only against its own encoder agrees with itself about
// a wrong Paeth predictor, and the result is not a crash — it is a capsule that looks slightly
// smeared and gets uploaded.
//
// The five filter rows below were worked out by hand, on paper, and the arithmetic is in the
// comments. Anything generated by running the same logic forwards would be the same mistake twice.

import { deflateSync } from "node:zlib";
import { crc32, decodePng, encodePng } from "../src/png.mjs";
import { ok, group, same } from "./harness.mjs";

const SIG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

const chunk = (type, body) => {
  const b = Buffer.from(body);
  const out = Buffer.alloc(b.length + 12);
  out.writeUInt32BE(b.length, 0);
  out.write(type, 4, "latin1");
  b.copy(out, 8);
  out.writeUInt32BE(crc32(out.subarray(4, 8 + b.length)), 8 + b.length);
  return out;
};

// rows is a list of [filterType, ...bytes]; everything else is the IHDR as written.
const png = ({ width, height, depth = 8, colour = 6, interlace = 0, rows, palette, trns, splits = 1, extra = [] }) => {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = depth;
  ihdr[9] = colour;
  ihdr[12] = interlace;
  const parts = [SIG, chunk("IHDR", ihdr)];
  if (palette) parts.push(chunk("PLTE", Buffer.from(palette)));
  if (trns) parts.push(chunk("tRNS", Buffer.from(trns)));
  const z = deflateSync(Buffer.from(rows.flat()));
  const per = Math.ceil(z.length / splits);
  for (let i = 0; i < z.length; i += per) parts.push(chunk("IDAT", z.subarray(i, i + per)));
  parts.push(...extra, chunk("IEND", Buffer.alloc(0)));
  return Buffer.concat(parts);
};

const pixels = (img) => Array.from(img.data);
const failed = (fn) => { try { fn(); return ""; } catch (e) { return e.message; } };

group("the CRC is the one in the spec", () => {
  // The IEND chunk's CRC is a published constant, so this pins the table to something that was not
  // computed here. Everything else in this file trusts it.
  ok(crc32(Buffer.from("IEND", "latin1")) === 0xae426082, "crc32('IEND') is 0xAE426082");
  ok(crc32(Buffer.from([])) === 0, "and an empty buffer is 0");
});

group("the five row filters, undone", () => {
  // Row 0 is unfiltered and is the ground everything below predicts from:
  //   px0 = 10,20,30,255   px1 = 40,50,60,255
  const base = [0, 10, 20, 30, 255, 40, 50, 60, 255];
  const two = (row) => pixels(decodePng(png({ width: 2, height: 2, rows: [base, row] }))).slice(8);

  ok(same(two([0, 9, 8, 7, 255, 6, 5, 4, 255]), [9, 8, 7, 255, 6, 5, 4, 255]),
    "None is the bytes as they are");

  // Sub: a is the pixel to the left, 0 for the first. 7+5=12; alpha 0+255 and 0+255.
  ok(same(two([1, 5, 5, 5, 255, 7, 7, 7, 0]), [5, 5, 5, 255, 12, 12, 12, 255]),
    "Sub adds the pixel to the left");

  // Up: b is the byte above. 3+10, 3+20, 3+30, 0+255, 4+40, ...
  ok(same(two([2, 3, 3, 3, 0, 4, 4, 4, 0]), [13, 23, 33, 255, 44, 54, 64, 255]),
    "Up adds the byte above");

  // Average: (a+b)>>1. First pixel a=0: (0+10)>>1=5, +1=6. (0+20)>>1=10, +1=11. (0+30)>>1=15, +1=16.
  // Alpha (0+255)>>1=127, +128=255. Second pixel: (6+40)>>1=23, +2=25. (11+50)>>1=30, +2=32.
  // (16+60)>>1=38, +2=40. (255+255)>>1=255, +0=255.
  ok(same(two([3, 1, 1, 1, 128, 2, 2, 2, 0]), [6, 11, 16, 255, 25, 32, 40, 255]),
    "Average is the floor of the mean of left and above");

  // PAETH, WITH ALL THREE ARMS TAKEN. A predictor that always answers "above" passes almost any
  // hand-rolled Paeth fixture, because above is what it usually picks — so this one is built so
  // that the red channel of each pixel resolves to a different neighbour. Row 0 is
  //   px0 = 10,20,30,255   px1 = 20,50,60,255   px2 = 16,50,60,255
  // and the filtered row below decodes to 100,20,30,255  25,50,60,255  23,50,60,255:
  //   i=0  a=0 b=10 c=0     p=10   pa=10 pb=0  pc=10  -> b=10,  90+10=100
  //   i=4  a=100 b=20 c=10  p=110  pa=10 pb=90 pc=100 -> a=100, 181+100=25 (mod 256)
  //   i=8  a=25 b=16 c=20   p=21   pa=4  pb=5  pc=1   -> c=20,  3+20=23
  const three = decodePng(png({
    width: 3, height: 2,
    rows: [[0, 10, 20, 30, 255, 20, 50, 60, 255, 16, 50, 60, 255], [4, 90, 0, 0, 0, 181, 0, 0, 0, 3, 0, 0, 0]],
  }));
  ok(same(pixels(three).slice(12), [100, 20, 30, 255, 25, 50, 60, 255, 23, 50, 60, 255]),
    "Paeth picks above, then left, then above-left, on three consecutive pixels");

  // One pixel wide means there is no left neighbour, so Paeth must degenerate to Up. A decoder
  // that reached past the start of the row for `a` returns something else here.
  const narrow = decodePng(png({ width: 1, height: 2, rows: [[0, 10, 20, 30, 255], [4, 1, 2, 3, 0]] }));
  ok(same(pixels(narrow).slice(4), [11, 22, 33, 255]), "and on a one-pixel row it is Up");
});

group("every colour type and depth the spec allows", () => {
  const one = (opts) => pixels(decodePng(png({ width: 2, height: 1, ...opts })));

  ok(same(one({ colour: 6, rows: [[0, 1, 2, 3, 4, 5, 6, 7, 8]] }), [1, 2, 3, 4, 5, 6, 7, 8]),
    "8-bit RGBA is itself");
  ok(same(one({ colour: 2, rows: [[0, 1, 2, 3, 4, 5, 6]] }), [1, 2, 3, 255, 4, 5, 6, 255]),
    "8-bit RGB gets an opaque alpha");
  ok(same(one({ colour: 0, rows: [[0, 7, 200]] }), [7, 7, 7, 255, 200, 200, 200, 255]),
    "greyscale becomes three equal channels");
  ok(same(one({ colour: 4, rows: [[0, 7, 128, 200, 0]] }), [7, 7, 7, 128, 200, 200, 200, 0]),
    "greyscale+alpha keeps its alpha");
  ok(same(one({ colour: 3, depth: 8, palette: [9, 9, 9, 1, 2, 3], rows: [[0, 1, 0]] }),
    [1, 2, 3, 255, 9, 9, 9, 255]), "indexed reads through the palette");

  // 16-bit takes the high byte: 0x0102 -> 1. A decoder reading the low byte returns 2 here.
  ok(same(one({ colour: 2, depth: 16, rows: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]] }),
    [1, 3, 5, 255, 7, 9, 11, 255]), "16-bit keeps the high byte of each sample");

  // Sub-byte depths are unpacked and scaled to 0..255, not left as 0..max.
  const bits = decodePng(png({ width: 8, height: 1, depth: 1, colour: 0, rows: [[0, 0b10100000]] }));
  ok(bits.data[0] === 255 && bits.data[4] === 0 && bits.data[8] === 255 && bits.data[12] === 0,
    "1-bit greyscale unpacks to 255 and 0, eight pixels to the byte");
  const nib = decodePng(png({ width: 2, height: 1, depth: 4, colour: 0, rows: [[0, 0xf0]] }));
  ok(nib.data[0] === 255 && nib.data[4] === 0, "and 4-bit scales 0..15 up to 0..255");
});

group("tRNS, which is three different things", () => {
  const idx = decodePng(png({
    width: 2, height: 1, colour: 3, palette: [1, 2, 3, 4, 5, 6], trns: [0, 128], rows: [[0, 0, 1]],
  }));
  ok(idx.data[3] === 0 && idx.data[7] === 128, "on an indexed image it is an alpha per palette entry");

  const grey = decodePng(png({ width: 2, height: 1, colour: 0, trns: [0, 7], rows: [[0, 7, 8]] }));
  ok(grey.data[3] === 0 && grey.data[7] === 255, "on greyscale it is the one level that is see-through");

  const rgb = decodePng(png({
    width: 2, height: 1, colour: 2, trns: [0, 1, 0, 2, 0, 3], rows: [[0, 1, 2, 3, 1, 2, 4]],
  }));
  ok(rgb.data[3] === 0 && rgb.data[7] === 255, "and on truecolour it is the one colour");
});

group("what it refuses, and what it says", () => {
  const rows = [[0, 1, 2, 3, 4]];
  ok(failed(() => decodePng(Buffer.from("not a png at all"))).includes("signature"),
    "something that is not a PNG is named as such");
  ok(failed(() => decodePng(png({ width: 1, height: 1, interlace: 1, rows })))
    .includes("interlaced"), "Adam7 is refused by name, with what to do about it");
  ok(failed(() => decodePng(png({ width: 1, height: 1, colour: 5, rows }))).includes("colour type 5"),
    "a colour type the spec does not define stops it");
  ok(failed(() => decodePng(png({ width: 1, height: 1, colour: 3, depth: 16, rows })))
    .includes("16-bit"), "and so does a depth that colour type cannot have");
  ok(failed(() => decodePng(png({ width: 1, height: 1, colour: 3, rows }))).includes("PLTE"),
    "an indexed image with no palette is not guessed at");
  ok(failed(() => decodePng(png({ width: 4, height: 4, rows }))).includes("truncated"),
    "a short pixel stream says how many bytes it was and how many it needed");
  ok(failed(() => decodePng(png({ width: 1, height: 1, rows: [[7, 1, 2, 3, 4]] }))).includes("filter type 7"),
    "a filter type outside 0-4 names the row");
  ok(failed(() => decodePng(png({
    width: 1, height: 1, colour: 3, depth: 8, palette: [1, 2, 3], rows: [[0, 4]],
  }))).includes("indexes palette entry 4"), "a palette index past the end of the palette is caught");

  const noPixels = Buffer.concat([png({ width: 1, height: 1, rows }).subarray(0, 33), chunk("IEND", Buffer.alloc(0))]);
  ok(failed(() => decodePng(noPixels)).includes("no IDAT"), "and a file with no image in it says so");
});

group("chunks are walked, not assumed", () => {
  const rows = [[0, 1, 2, 3, 4, 5, 6, 7, 8], [0, 9, 10, 11, 12, 13, 14, 15, 16]];
  const whole = pixels(decodePng(png({ width: 2, height: 2, rows })));
  // The real plate arrives as 51 IDATs. A decoder that took the first one gets a truncation error
  // rather than a wrong image, but only because zlib notices — worth pinning anyway.
  ok(same(pixels(decodePng(png({ width: 2, height: 2, rows, splits: 6 }))), whole),
    "a pixel stream split across six IDAT chunks is the same image");
  ok(same(pixels(decodePng(png({
    width: 2, height: 2, rows, extra: [chunk("tEXt", Buffer.from("who\0knows"))],
  }))), whole), "and an ancillary chunk it has never heard of is stepped over");
});

group("what it writes comes back", () => {
  const width = 37, height = 21;
  const data = new Uint8Array(width * height * 4);
  for (let i = 0; i < data.length; i += 4) {
    data[i] = (i * 7) & 0xff;
    data[i + 1] = (i * 13) & 0xff;
    data[i + 2] = 255 - ((i * 3) & 0xff);
    data[i + 3] = i % 97 === 0 ? 0 : 255;
  }
  const back = decodePng(encodePng({ width, height, data }));
  ok(back.width === width && back.height === height, "the round trip is the same size");
  ok(same(pixels(back), Array.from(data)), "and every byte of it survives, alpha included");

  // Adaptive filtering has to actually pick different rows or it is not adaptive, and a bug that
  // always answers 0 would still round-trip perfectly.
  const flat = new Uint8Array(64 * 8 * 4).fill(200);
  const encoded = encodePng({ width: 64, height: 8, data: flat });
  ok(encoded.length < 200, "a flat field compresses to almost nothing");
  ok(same(pixels(decodePng(encoded)), Array.from(flat)), "and still decodes to what went in");

  const solo = decodePng(encodePng({ width: 1, height: 1, data: new Uint8Array([1, 2, 3, 4]) }));
  ok(same(pixels(solo), [1, 2, 3, 4]), "a single pixel is not a special case");
});
